### ISSUE TITLE
win build Configures the VS environment

### ISSUE THREAD

**Issue by Y7NINE** [LLNL/LEAP#113] opened 2024-10-11 01:39 UTC
Hello, when I try to generate the win_build configuration VS environment call function, there are always the following warnings. Is there any good solution? (This problem may be some brainless. I am a beginner who is interested in computers.
![image](https://github.com/user-attachments/assets/9a6eecdf-23e6-4921-9161-e729640c600a)

**Comment by hws203** [comment] 2024-10-11 02:28
@Y7NINE parameters.cpp file may not be compiled at your project.

**Comment by Y7NINE** [comment] 2024-10-11 05:47
> @Y7NINE parameters.cpp file may not be compiled at your project.

Okay, teacher. I tried recompiling, but I still encountered these issues. Below is my C++ code. If possible, could you generate it in your project? I want to understand whether the issue is with my usage or the environment.

**Comment by Y7NINE** [comment] 2024-10-11 05:49
@hws203 
Okay, teacher. I tried recompiling, but I still encountered these issues. Below is my C++ code. If possible, could you generate it in your project? I want to understand whether the issue is with my usage or the environment.

------------------------------------------------------------------------

#include "filtered_backprojection.h"
#include "parameters.h"

int main() {
    // Initialize parameters object
    parameters params;

    // Set relevant parameters (e.g., geometry, GPU usage, etc.)
    params.geometry = parameters::CONE;
    params.helicalPitch = 0.0;
    params.whichGPU = -1; // -1 means using CPU, set to 0 or positive integer to use GPU

    // Initialize projection data (g) and result array (f)
    int numAngles = 180; // Number of angles
    int numRows = 512;   // Number of rows in the projection data
    int numCols = 512;   // Number of columns in the projection data

    float* g = (float*)malloc(sizeof(float) * numAngles * numRows * numCols);
    float* f = (float*)malloc(sizeof(float) * params.numX * params.numY * params.numZ); // Reconstructed volume data

    // Fill in the projection data for g (assume you have data available)
    // For example: load projection data from a file or generate it

    // Create filteredBackprojection object
    filteredBackprojection fbp;

    // Execute the FBP algorithm
    bool result = fbp.execute(g, f, &params, true); // true indicates data is on the CPU

    if (result) {
        printf("FBP execution succeeded!\n");
    } else {
        printf("FBP execution failed!\n");
    }

    // Free allocated memory
    free(g);
    free(f);

    return 0;
}

**Comment by hws203** [comment] 2024-10-11 20:59
It is not related to your main code, it is a environment issue. So you need to check whether your project environment include the parameters.cpp file.

**Comment by Y7NINE** [comment] 2024-10-12 06:19
@hws203 Haha, thanks for the heads-up! Looks like I need to debug my environment as much as my code. Guess my parameters need more attention than my actual code!

**Comment by Y7NINE** [comment] 2024-10-13 13:00
@hws203 I apologize for bothering you again. I've become quite fascinated with this program recently, and I've run into some issues. I'm currently trying to implement the Python version of the FBP program in C++. I'm seeking help with a humble and eager-to-learn attitude. 
This is my python program
![image](https://github.com/user-attachments/assets/b38f786c-0bd4-4f7f-b195-39a79baa0c38)
I saw the initialization parameters in parameters.cpp so I tried to set the same parameters as the ones called in python
![image](https://github.com/user-attachments/assets/791056c0-6946-48e2-b5f1-bf6c7ad00b0b)
In C++, I also refer to the way of another author to put the projection data into the three-dimensional way
![image](https://github.com/user-attachments/assets/40fd7182-9336-4c12-8689-3b762da0feb9)
![image](https://github.com/user-attachments/assets/c12a59d6-c47c-44e4-aff4-b493da8d2170)
However, there is still an endless loop in the fft but instead of reporting an error, the cpu keeps showing full
![image](https://github.com/user-attachments/assets/4f123720-7a96-4dba-9dec-d30ac42f69e2)
Below is my c++ code. I suspect that my input method is not quite right. Can you give me some suggestions

---------------------------I'm really sorry to bother you by asking questions these days-------------------------


#include "filtered_backprojection.h"
#include "parameters.h"


#define M_PI 3.1415926535897932846

int main() {
    // Initialize projection data (g) and result array (f)
    int numAngles = 800; // Number of angles
    int numRows = 1024;   // Number of rows in the projection data
    int numCols = 1328;   // Number of columns in the projection data
    float pixelSize = 0.3;
    float na = numAngles;
    float* betas_rad = (float*)malloc(sizeof(float) * na); //投影角度内存
    for (int idx = 0; idx < na; idx++)
    {
        betas_rad[idx] = float(-idx) / float(na) * 360.f; // 计算角度
    }
    // Initialize parameters object
    parameters params;

    // Set relevant parameters (e.g., geometry, GPU usage, etc.)
    params.geometry = parameters::CONE;
    params.helicalPitch = 0.0;
    params.whichGPU = -1; // -1 means using CPU, set to 0 or positive integer to use GPU
    params.numX = 1024;
    params.numY = 1024;
    params.numZ = 400;
    params.sod = 566.52;
    params.sdd = 1009.04;
    params.pixelWidth = 0.3;
    params.pixelHeight = 0.3;
    float xh_offset = 178.97;
    params.centerCol = 0.5 * (numCols - 1) - xh_offset / pixelSize;
    params.centerRow = 0.5 * (numRows - 1);
    params.voxelHeight = 0.371;
    params.voxelWidth = 0.3525;
    params.numAngles = 800;
    params.angularRange = 360;
    params.phis = betas_rad;
    params.numRows = 1024;   // Number of rows in the projection data
    params.numCols = 1328;
    params.offsetScan = true;
    params.truncatedScan = true;

    float* g = (float*)malloc(sizeof(float) * numAngles * numRows * numCols);//物体投影数据
    float* f = (float*)malloc(sizeof(float) * params.numX * params.numY * params.numZ); // Reconstructed volume data

    //++++++++++++object projection+++++++++++++
    FILE* fid = NULL;
    printf("Start to read object projection!\n");
    const char* proj_file_1 = { "proj-42-841.raw" }; 
    fid = fopen(proj_file_1, "rb");
    if (fid == NULL) { printf("\nERROR: Could not open pre-weight file %s\n", proj_file_1); }
    fread(g, sizeof(float), numAngles * numRows * numCols, fid);
    fclose(fid);
    printf("Reading object projection is done!\n");

    // Fill in the projection data for g (assume you have data available)
    // For example: load projection data from a file or generate it

    // Create filteredBackprojection object
    filteredBackprojection fbp;

    // Execute the FBP algorithm
    bool result = fbp.execute(g, f, &params, true); // true indicates data is on the CPU
    //bool result = fbp.execute(g, f, &*params, false);
    if (result) {
        printf("FBP execution succeeded!\n");
    }
    else {
        printf("FBP execution failed!\n");
    }

    const char* fname_out = "Half-fanFDK-.raw"; 
    printf("Writing output image to file....\n");
    fid = fopen(fname_out, "wb");
    fwrite(f, sizeof(float), 1024 * 1024 *400, fid);
    fclose(fid);
    printf("DONE!!\n");

    // Free allocated memory
    free(g);
    free(f);

    return 0;
}

**Comment by kylechampley** [comment] 2024-10-13 22:45
Hello.  At first glance, everything looks correct.  The CPU routines in LEAP have fell behind and are not supported well at this point.  The CPU-based filtering is especially slow, so maybe start with a small test case to see if things are working properly.  For example, just use one detector row.  Do you not have access to a GPU?

And one more suggestion.  I highly recommend that you only use the API through the tomographicModels class if you are using the C++ API.  The other classes were not designed to be used.

**Comment by Y7NINE** [comment] 2024-10-14 03:40
@kylechampley  Thank you very much for your advice but there are still some problems copying the python order to call the c++ program past but the result is non-zero. I verified that my input and parameters are the same as in the python program. Is there a problem with my c++ api use
![image](https://github.com/user-attachments/assets/f6bbfd60-892d-418c-a9cf-dec14fa67caa)
The two True parameters in the python program I modified in parameters.cpp
![image](https://github.com/user-attachments/assets/8d207221-c01d-4efb-90ef-d73d753d55d9)
![image](https://github.com/user-attachments/assets/427d7057-6a34-4401-98c8-c0b3f261b1f0)
The result is zero
![image](https://github.com/user-attachments/assets/abe561a0-d503-40d7-bff5-e03d52851bb8)
Is there a problem with how I call it
I can use the GPU you said, but I have not figured out how to pass the parameters of cuda, will the following error appear
![image](https://github.com/user-attachments/assets/77c1d707-1a45-4343-a6b9-59b43f659c78)

#include "filtered_backprojection.h"
#include "parameters.h"
#include "tomographic_models.h"
#define M_PI 3.1415926535897932846

int main() {
    // Initialize projection data (g) and result array (f)
    int numAngles = 800; // Number of angles
    int numRows = 1024;   // Number of rows in the projection data
    int numCols = 1328;   // Number of columns in the projection data
    float pixelWidth = 0.3;
    float pixelHeight = 0.3;
    int numX = 1024;
    int numY = 1024;
    int numZ = 400;
    float xh_offset = 178.97;
    float centerCol = 0.5 * (numCols - 1) - xh_offset / pixelWidth;
    float centerRow = 0.5 * (numRows - 1);
    float sod = 566.52;
    float sdd = 1009.04;
    float voxelHeight = 0.3525;
    float voxelWidth = 0.371;
    float offsetX = 0.0;
    float offsetY = 0.0;
    float offsetZ = 0.0;
 
    float* phis = (float*)malloc(sizeof(float) * numAngles); 
    for (int idx = 0; idx < numAngles; idx++)
    {
        phis[idx] = float(-idx) / float(numAngles) * 360.f;
    }

    float* g = (float*)malloc(sizeof(float) * numAngles * numRows * numCols);
    float* f = (float*)malloc(sizeof(float) * numX * numY * numZ); // Reconstructed volume data

    //++++++++++++object projection+++++++++++++
    FILE* fid = NULL;
    printf("Start to read object projection!\n");
    const char* proj_file_1 = { "proj-42-841.raw" };
    fid = fopen(proj_file_1, "rb");
    if (fid == NULL) { printf("\nERROR: Could not open pre-weight file %s\n", proj_file_1); }
    fread(g, sizeof(float), numAngles * numRows * numCols, fid);
    fclose(fid);
    printf("Reading object projection is done!\n");

    // Create tomographicModels object
    tomographicModels fbp;

    // Execute the FBP algorithm
    bool set_conebeam = fbp.set_conebeam(numAngles, numRows, numCols, pixelHeight, pixelWidth, centerRow, centerCol, phis, sod, sdd);
    bool set_volume = fbp.set_volume(numX, numY, numZ, voxelWidth, voxelHeight, offsetX, offsetY, offsetZ);
    bool parameters = fbp.print_parameters();
    
    bool fdk = fbp.FBP_cpu(g,f);

    if (fdk) {
        printf("FBP execution succeeded!\n");
    }
    else {
        printf("FBP execution failed!\n");
    }

    const char* fname_out = "Half-fanFBP-.raw";
    printf("Writing output image to file....\n");
    fid = fopen(fname_out, "wb");
    fwrite(f, sizeof(float), numX * numY * numZ, fid);
    fclose(fid);
    printf("DONE!!\n");

    // Free allocated memory
    free(g);
    free(f);

    return 0;
}

**Comment by kylechampley** [comment] 2024-10-14 14:59
It's hard to diagnose the issue because I only have partial information here.  Anyway, one issue I see here is that you are using FBP_cup and FBP_gpu.  These functions are deprecated and are only there for backward compatibility.  Just use the FBP function in the tomographicModels class and hand it data on the CPU.  It will handle all the CPU-to-GPU data transfers for you and there should be nothing you need to do.

Also, I don't recommend changing the defaults in parameters.cpp.  If you want to change these variables just do this:
```
tomographicModels leapct;
leapct.params.set_offsetScan(true);
leapct.params.set_truncatedScan(true);
```

**Comment by Y7NINE** [comment] 2024-10-15 01:29
@kylechampley Thank you so much for my confusion about Just use the FBP function in the tomographicModels class
![image](https://github.com/user-attachments/assets/c51dbd57-9ae3-4f9c-b959-92b808de0f93)
I tried all the FPB functions in the class and the results were all zeros but my python program was able to reconstruct the image
![image](https://github.com/user-attachments/assets/7792d9d6-2402-4e76-9cfe-3151b1eb900e)
![image](https://github.com/user-attachments/assets/f906d340-5a8c-4e61-9c68-083a6daa1fc6)
![image](https://github.com/user-attachments/assets/c73cc9b5-8fc5-4be5-b8d0-c585050b92fa)
![image](https://github.com/user-attachments/assets/24e1f531-73d8-47f7-b650-3809a8a6d781)
I uploaded my data and my programs in a zip pack
https://drive.google.com/file/d/1NuJ7WbKAl0hjpTsSXhPbUch7ImD1_sWp/view

**Comment by Y7NINE** [comment] 2024-10-15 02:07
c++ program upload error I put here
#include "filtered_backprojection.h"
#include "parameters.h"
#include "tomographic_models.h"
#define M_PI 3.1415926535897932846

int main() {
    // Initialize projection data (g) and result array (f)
    int numAngles = 800; // Number of angles
    int numRows = 1024;   // Number of rows in the projection data
    int numCols = 1328;   // Number of columns in the projection data
    float pixelWidth = 0.3;
    float pixelHeight = 0.3;
    int numX = 1024;
    int numY = 1024;
    int numZ = 400;
    float xh_offset = 178.97;
    float centerCol = 0.5 * (numCols - 1) - xh_offset / pixelWidth;
    float centerRow = 0.5 * (numRows - 1);
    float sod = 566.52;
    float sdd = 1009.04;
    float voxelHeight = 0.3525;
    float voxelWidth = 0.371;
    float offsetX = 0.0;
    float offsetY = 0.0;
    float offsetZ = 0.0;
 
    float* phis = (float*)malloc(sizeof(float) * numAngles); 
    for (int idx = 0; idx < numAngles; idx++)
    {
        phis[idx] = float(-idx) / float(numAngles) * 360.f;
    }

    float* g = (float*)malloc(sizeof(float) * numAngles * numRows * numCols);
    float* f = (float*)malloc(sizeof(float) * numX * numY * numZ); // Reconstructed volume data

    //++++++++++++object projection+++++++++++++
    FILE* fid = NULL;
    printf("Start to read object projection!\n");
    const char* proj_file_1 = { "proj-42-841.raw" };
    fid = fopen(proj_file_1, "rb");
    if (fid == NULL) { printf("\nERROR: Could not open pre-weight file %s\n", proj_file_1); }
    fread(g, sizeof(float), numAngles * numRows * numCols, fid);
    fclose(fid);
    printf("Reading object projection is done!\n");

    //// Create tomographicModels object
    //tomographicModels fbp;

    //// Execute the FBP algorithm
    //bool set_conebeam = fbp.set_conebeam(numAngles, numRows, numCols, pixelHeight, pixelWidth, centerRow, centerCol, phis, sod, sdd);
    //bool set_volume = fbp.set_volume(numX, numY, numZ, voxelWidth, voxelHeight, offsetX, offsetY, offsetZ);
    //bool parameters = fbp.print_parameters();
    //
    //bool fdk = fbp.FBP(g,f);

    tomographicModels leapct;
   
    leapct.set_conebeam(numAngles, numRows, numCols, pixelHeight, pixelWidth, centerRow, centerCol, phis, sod, sdd);
    leapct.set_volume(numX, numY, numZ, voxelWidth, voxelHeight, offsetX, offsetY, offsetZ);
    leapct.params.set_offsetScan(true);
    leapct.params.set_truncatedScan(true);
    leapct.print_parameters();
    leapct.doFBP(g, f, true);
    printf("FBP execution failed!\n");
   

    const char* fname_out = "Half-fanFBP-.raw";
    printf("Writing output image to file....\n");
    fid = fopen(fname_out, "wb");
    fwrite(f, sizeof(float), numX * numY * numZ, fid);
    fclose(fid);
    printf("DONE!!\n");

    // Free allocated memory
    free(g);
    free(f);

    return 0;
}

**Comment by Y7NINE** [comment] 2024-10-15 03:25
![image](https://github.com/user-attachments/assets/4f4a902d-b4c2-49a4-bd81-63a859c26e9b)
In python I put air in it but the c++ program still runs with all zeros


import numpy as np
from leap_preprocessing_algorithms import *
from leapctype import tomographicModels
leapct = tomographicModels()
import tifffile as tiff


numAngles = 800
numRows = 1024
numCols = 1328
pixelSize = 0.3
xh_offset = 178.97
centerCol = 0.5 * (numCols - 1) - xh_offset / pixelSize
sod = 566.52
sdd = 1009.04

# angles = np.linspace(-180, 180, numAngles).astype(np.float32)

na = numAngles
betas_rad = np.zeros(na, dtype=np.float32)  # Example of a radians array

for idx in range(na):
    betas_rad[idx] = -float(idx) / float(na) * 2.0 * np.pi  # Calculating radians

angles = np.degrees(betas_rad)

leapct.set_conebeam(numAngles, numRows, numCols, pixelSize, pixelSize, 0.5 * (numRows - 1), centerCol, angles, sod, sdd)
leapct.set_offsetScan(True)
leapct.set_truncatedScan(True)
leapct.set_volume(1024, 1024, 400, 0.371, 0.3525, 0, 0, 0)
leapct.print_parameters()

g = tiff.imread(r'E:\LEAP-1.23\LEAP-1.23\myFDK\proj-42-841.tif')

air = tiff.imread(r'E:\LEAP-1.23\LEAP-1.23\myFDK\air.tif')

ROI = [30, 80, 950, 1000]
makeAttenuationRadiographs(leapct, g, air, None, ROI)

vol = leapct.allocateVolume(0)
leapct.FBP(g, vol)
leapct.display(vol)

raw_file_path = './proj_1014.raw'
vol.tofile(raw_file_path)
print(f"The reconstruction result has been saved as {raw_file_path}")

**Comment by Y7NINE** [comment] 2024-10-15 04:50
The initial suspicion is that my argument did not pass in or did not call the function successfully. I am trying to modify it. Do you have a better idea

**Comment by kylechampley** [comment] 2024-10-16 14:51
I don't have access to the data on your good drive.  Can you grant me access?

**Comment by Y7NINE** [comment] 2024-10-17 00:51
@kylechampley Oh, my God, I forgot there was something about it and now it's open

**Comment by Y7NINE** [comment] 2024-10-17 00:58
This is my data set and it should be accessible now
https://drive.google.com/file/d/1McaHp96NDRYJvrKwkP-lw-Q42X0zH8GY/view?usp=sharing

**Comment by kylechampley** [comment] 2024-10-17 02:56
You pretty much had it figured out.  You just forgot to convert your data from raw to attenuation.  In the Python script this was handled by the makeAttenuationRadiographs function.  Anyway, just add the following to your script just after you read in your projection data.

```
float* air_scan = (float*)malloc(sizeof(float) * numRows * numCols);
const char* air_file = { "air.raw" };
fid = fopen(air_file, "rb");
if (fid == NULL) { printf("\nERROR: Could not open pre-weight file %s\n", air_file); }
fread(air_scan, sizeof(float), numRows * numCols, fid);
fclose(fid);

for (int iview = 0; iview < numAngles; iview++)
{
  float* aProj = &g[iview * numRows * numCols];
  for (int ii = 0; ii < numRows*numCols; ii++)
  {
	  aProj[ii] = -log(aProj[ii] / air_scan[ii]);
  }
}
free(air_scan);
```

**Comment by Y7NINE** [comment] 2024-10-17 03:10
@kylechampley I have tried this method but the result in C++ program is still 0. Can your C++ program have a normal value

**Comment by Y7NINE** [comment] 2024-10-17 03:17
If you can reconstruct the image in C++ normally, can you share the code? I uploaded a CPP program in the file

**Comment by Y7NINE** [comment] 2024-10-17 03:45
The air uploaded before will show inf in CPP, but it can be calculated normally in python. In order to avoid the error caused by inf in cpp, I uploaded a new air
![image](https://github.com/user-attachments/assets/9b71dc91-ed84-4300-83d0-c1d05f1695b4)
After uploading the new air, the cpp program will display the value normally
![image](https://github.com/user-attachments/assets/415a4185-aee9-490e-8111-27f2f442d0e6)
This is the new air 
https://drive.google.com/file/d/1_GNm3gVX5DrIvd_2KwCbkwTBckCTn829/view?usp=sharing

**Comment by Y7NINE** [comment] 2024-10-17 07:41
I tried to find the error and the rest of the code remained unchanged, so I changed the true in DoFBP to false. The following error occurred. Is it possible that this is the reason why the true problem also occurred
![image](https://github.com/user-attachments/assets/7d5b64e2-234c-41ec-91a4-747b7229f3ec)

**Comment by kylechampley** [comment] 2024-10-17 12:45
I did not need this new air scan file; the old one worked just fine.  I'm not sure what is going wrong on your end.  Below is the exact code I used.

```
void test_script()
{
	// Initialize projection data (g) and result array (f)
	int numAngles = 800; // Number of angles
	int numRows = 1024;   // Number of rows in the projection data
	int numCols = 1328;   // Number of columns in the projection data
	float pixelWidth = 0.3;
	float pixelHeight = 0.3;
	int numX = 1024;
	int numY = 1024;
	int numZ = 400;
	float xh_offset = 178.97;
	float centerCol = 0.5 * (numCols - 1) - xh_offset / pixelWidth;
	float centerRow = 0.5 * (numRows - 1);
	float sod = 566.52;
	float sdd = 1009.04;
	float voxelHeight = 0.3525;
	float voxelWidth = 0.371;
	float offsetX = 0.0;
	float offsetY = 0.0;
	float offsetZ = 0.0;

	float* phis = (float*)malloc(sizeof(float) * numAngles);
	for (int idx = 0; idx < numAngles; idx++)
	{
		phis[idx] = float(-idx) / float(numAngles) * 360.f;
	}

	float* g = (float*)malloc(sizeof(float) * numAngles * numRows * numCols);
	float* f = (float*)malloc(sizeof(float) * numX * numY * numZ); // Reconstructed volume data

	//++++++++++++object projection+++++++++++++
	FILE* fid = NULL;
	printf("Start to read object projection!\n");
	const char* proj_file_1 = { "C:\\Users\\champley\\Downloads\\FBP_cpp\\proj-42-841.raw" };
	fid = fopen(proj_file_1, "rb");
	if (fid == NULL) { printf("\nERROR: Could not open pre-weight file %s\n", proj_file_1); }
	fread(g, sizeof(float), numAngles * numRows * numCols, fid);
	fclose(fid);
	printf("Reading object projection is done!\n");

	float* air_scan = (float*)malloc(sizeof(float) * numRows * numCols);
	const char* air_file = { "C:\\Users\\champley\\Downloads\\FBP_cpp\\air.raw" };
	fid = fopen(air_file, "rb");
	if (fid == NULL) { printf("\nERROR: Could not open pre-weight file %s\n", air_file); }
	fread(air_scan, sizeof(float), numRows * numCols, fid);
	fclose(fid);

	for (int iview = 0; iview < numAngles; iview++)
	{
		float* aProj = &g[iview * numRows * numCols];
		for (int ii = 0; ii < numRows*numCols; ii++)
		{
			aProj[ii] = -log(aProj[ii] / air_scan[ii]);
		}
	}
	free(air_scan);

	//// Create tomographicModels object
	//tomographicModels fbp;

	//// Execute the FBP algorithm
	//bool set_conebeam = fbp.set_conebeam(numAngles, numRows, numCols, pixelHeight, pixelWidth, centerRow, centerCol, phis, sod, sdd);
	//bool set_volume = fbp.set_volume(numX, numY, numZ, voxelWidth, voxelHeight, offsetX, offsetY, offsetZ);
	//bool parameters = fbp.print_parameters();
	//
	//bool fdk = fbp.FBP(g,f);

	tomographicModels leapct;

	leapct.set_conebeam(numAngles, numRows, numCols, pixelHeight, pixelWidth, centerRow, centerCol, phis, sod, sdd);
	leapct.set_volume(numX, numY, numZ, voxelWidth, voxelHeight, offsetX, offsetY, offsetZ);
	leapct.params.set_offsetScan(true);
	leapct.params.set_truncatedScan(true);
	leapct.print_parameters();
	leapct.doFBP(g, f, true);
	printf("FBP execution failed!\n");


	const char* fname_out = "Half-fanFBP-.raw";
	printf("Writing output image to file....\n");
	fid = fopen(fname_out, "wb");
	fwrite(f, sizeof(float), numX * numY * numZ, fid);
	fclose(fid);
	printf("DONE!!\n");

	// Free allocated memory
	free(g);
	free(f);
}
```

**Comment by kylechampley** [comment] 2024-10-17 12:47
You should definitely get an error if you change that argument to false.  The argument is called "data_on_cpu".  If you specify this as false, then you are saying the data pointers refer to data on the GPU which in your case is not true.

**Comment by Y7NINE** [comment] 2024-10-17 12:55
Thank you very much for your advice. I have further eliminated some problems. I wonder if there is a problem with my environment. Could you please give me a configured project link? When I tested the code, I created a new project and directly added the CPP CUH CUH file needed without using pip The dll in win_build generated by insatll and the cuda12.6 I am using I suspect there is something wrong with my VS project setup

**Comment by kylechampley** [comment] 2024-10-17 13:08
I'm sorry, I cannot share these files.  I'm not sure what the issue is.

**Comment by Y7NINE** [comment] 2024-10-17 13:53
Well, can I ask you about your environment such as CUDA version CUDNN version and VS version
But that doesn't stop LEAP from being a very interesting package. That's the end of my question. Thank you very much for your help on this issue

**Comment by Y7NINE** [comment] 2024-10-18 01:39
@kylechampley 
Thank you very much for your suggestions; they have inspired me. For some reason, after reinstalling some environment settings and configuring VS in release mode, my computer was able to produce correct results. I sincerely appreciate it!
![image](https://github.com/user-attachments/assets/5dea6aaa-9bfa-4486-94a2-1a6fd388e624)

**Comment by kylechampley** [comment] 2024-10-18 02:26
Congratulations!  Thanks for not giving up.

I'm going to close this issue, but feel free to open another issue if something comes up.

**Closed by kylechampley** 2024-10-18 02:26 UTC
